# Generated by Django 4.2.20 on 2025-04-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usermanage", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/avatar.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
